version: "3.9"
services:
  web:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend

  game_logic:
    build: ./backend/logic_service
    ports:
      - "8008:8008"
    networks:
      - frontend
      - backend
    depends_on:
      - db_service

  db_service:
    build: ./backend/datastorage
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

networks:
  frontend:
    name: frontend
    external: true
  backend:
    name: backend


